ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes   # Enable keyboard RGB underglow
TAP_DANCE_ENABLE = yes
SPLIT_KEYBOARD = yes
COMBO_ENABLE = yes
OLED_DRIVER_ENABLE = yes
HAPTIC_ENABLE += DRV2605L

BOOTMAGIC_ENABLE = no      # Virtual DIP switch configuration
BONGO_CAT_ENABLE = no
EXTRAFLAGS += -flto
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
UNICODE_ENABLE = no
AUDIO_ENABLE = no
CONSOLE_ENABLE = no
TERMINAL_ENABLE = no
NKRO_ENABLE = no           # USB Nkey Rollover
BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality on B7 by default
MIDI_ENABLE = no           # MIDI support
BLUETOOTH_ENABLE = no      # Enable Bluetooth with the Adafruit EZ-Key HID
AUDIO_ENABLE = no          # Audio output on port C6
